### PR TITLE
fix: support proxy setting from env vars

### LINKED ISSUE #54: Support proxies HTTP_PROXY & HTTPS_PROXY
Support HTTP/S_PROXY env vars being set and honoring them.

We may need some proxies when using corporate vpn, this should be honored by http clients like cassowary.

### PR DESCRIPTION
**Pull request by kevdowney**
Fixes #54 

Support HTTP_PROXY, HTTPS_PROXY or NO_PROXY being set as environment variables.

e.g., `export HTTPS_PROXY=http://127.0.0.1:38080`

### CODE REVIEW

File: pkg/client/load.go [hunk 1]
```diff
@@ -102,6 +102,7 @@ func (c *Cassowary) runLoadTest(outPutChan chan<- durationMetrics, workerChan ch
 		}
 
 		request = request.WithContext(httptrace.WithClientTrace(context.Background(), trace))
+		c.Client.Transport.(*http.Transport).Proxy = http.ProxyFromEnvironment
```
Comment (rogerwelin) [inline pkg/client/load.go:105]: could you please move this logic to where c.Client is initialized in the Coordinate method

**Review by rogerwelin — CHANGES_REQUESTED** [review]

File: pkg/client/load.go (hunk 1 above)
Comment (rogerwelin) [reply pkg/client/load.go:105]: and thanks for the contribution, I apologise for late reply

Comment (kevdowney) [reply pkg/client/load.go]: Done.
